name: RedAntiKillerPotions
main: de.redstoneworld.redantikillerpotions.RedAntiKillerPotions
version: 1.1.2
api-version: 1.19
description: This is a small plugin to prevent killer potions.
authors: [RedstoneFuture]
website: https://redstoneworld.de