name: RedAntiKillerPotions
main: de.redstoneworld.redantikillerpotions.RedAntiKillerPotions
version: 0.0.1
api-version: 1.17
description: This is a small plugin to prevent killer potions.
authors: [RedstoneFuture]
website: https://redstoneworld.de